### PR TITLE
feat: add large and small size variants to the TextButton

### PR DESCRIPTION
**Pull request by satazor**
Similar to the FeedbackMessage.

### CODE REVIEW

**Comment by satazor** [comment]
Note that this is a breaking change, we need to be careful to fix things in the web project.

**Review by PedroMiguelSS — APPROVED** [review]
Great 👍 @dominguesgm will take care of `TextButton` usage changes.

**Review by dominguesgm — APPROVED** [review]
Looks good to me, as @PedroMiguelSS said I'll be looking into the required changes in `Nomios-web`

**Comment by satazor** [comment]
Alright, can we merge this then?

**Pull request merged**
