### PR TITLE
chore: remove FeedbackMessage textColor property

### PR DESCRIPTION
**Pull request by satazor**
In favor of modifying via style or classnames.

### CODE REVIEW

**Comment by satazor** [comment]
This is something I decided to improve but wasn't really necessary. Needs to be tested within the web app but it's working within the TextInput.

**Review by PedroMiguelSS — APPROVED** [review]
All good for me. But what's the reason for this change? Was it just to remove one unnecessary prop?

**Comment by satazor** [comment]
We never had a CSS style via a custom property, we always used either `style` or `className`. It was to keep consistency.

**Comment by PedroMiguelSS** [comment]
Alright, got it 👍

**Pull request merged**
